import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Tropical Tea',
      category: 'fruit-tea',
      image: '/images/fruit-tea-1.png',
      price: 15,
      countInStock: 10,
      brand: 'Jack',
      rating: 4.5,
      numReviews: 10,
      description: 'high-quality',
    },
    {
      name: 'Milk Tea Okinawa',
      category: 'milk-tea',
      image: '/images/milk-tea-1.png',
      price: 10,
      countInStock: 0,
      brand: 'Jack',
      rating: 3,
      numReviews: 10,
      description: 'high-quality',
    },
    {
      name: 'Milk Tea Matcha',
      category: 'milk-tea',
      image: '/images/milk-tea-2.png',
      price: 25,
      countInStock: 16,
      brand: 'Jack',
      rating: 5,
      numReviews: 10,
      description: 'high-quality',
    },
    {
      name: 'Smoothie Strawberry',
      category: 'smoothie',
      image: '/images/smoothie-1.png',
      price: 20,
      countInStock: 13,
      brand: 'Jack',
      rating: 4,
      numReviews: 10,
      description: 'high-quality',
    },
    {
      name: 'Oloong Tea',
      category: 'tea',
      image: '/images/tea-1.png',
      price: 10,
      countInStock: 15,
      brand: 'Jack',
      rating: 3,
      numReviews: 10,
      description: 'high-quality',
    },
    {
      name: 'Black Tea',
      category: 'tea',
      image: '/images/tea-2.png',
      price: 12,
      countInStock: 20,
      brand: 'Jack',
      rating: 4.5,
      numReviews: 10,
      description: 'high-quality',
    },
  ],
};

export default data;
